title: scratch3-jiggle-a-sprite
hero_image: images/banner.png
description: scratch3-jiggle-a-sprite description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
