---
title: Zatřeste s postavou
hero_image: images/banner.png
description: Zatřeste se sprajtem
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Zatřeste s postavou
