---
title: Fai oscillare uno sprite
hero_image: images/banner.png
description: Fai oscillare uno sprite
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Fai oscillare uno sprite
